require          'bundler/setup'
require          'sinatra'
require          'sinatra/activerecord/rake'
require          'json'
require          'pp'
require_relative 'config/database'
require_relative 'lib/json'

desc "Launch a console with our environment loaded"
task :console do
  require          'irb'
  require_relative 'lib/json'
  ARGV.clear
  $PROGRAM_NAME = 'irb'
  IRB.start
end

task :importer do
  data = JSON.parse(File.read('data/employee_department.json'))

  data["employees"].each do |empl|
    unless Json::Employee.find_by_first_name(empl["first_name"])
      
      Json::Employee.create(first_name: empl["first_name"],
                            last_name:  empl["last_name"],
                            department: empl["department"],
                            job:        empl["job"])
    end
  end
end
  

# task :parser do
#   json = File.read('data/employees.json')
#   empls = JSON.parse(json)
# 
#   pp empls
#   
#   pp "The CFO is: #{empls["CFO"]}"
#   
#   pp "The people in HR are: #{empls["Human Resources"][0]}"
# end
# 
# task :parser2 do
#   json = File.read('data/employee_department.json')
#   empls = JSON.parse(json)
#   
#   pp "The first employee #{empls["employees"]}"
# end